export const missionsData = {
  primary: [
    {
      id: 'artemis',
      title: 'Allein inmitten der Sterne',
      subtitle: 'Artemis Path',
      priority: 3,
      tag: 'MAIN STORY',
      tagColor: 'cyan',
      description: 'The main storyline following Artemis, the explorer.',
      unlocks: 'Portals, new galaxies, most game features',
      currentQuest: 'Artemis, der Entdecker',
      tip: 'This drives progression the most. Focus here first!',
      icon: '🌌',
    },
    {
      id: 'anomaly',
      title: 'Die Weltraumanomalie',
      subtitle: 'Space Anomaly',
      priority: 3,
      tag: 'PARALLEL',
      tagColor: 'blue',
      description: 'Introduces the Nexus (multiplayer hub), Nada & Polo.',
      unlocks: 'Blueprints, multiplayer missions, Nexus shop',
      currentQuest: 'Jenseits des Systems?',
      tip: 'Runs parallel to Artemis Path. Visit the Anomaly when prompted.',
      icon: '🔮',
    },
    {
      id: 'atlas',
      title: 'Der Weg des Atlas',
      subtitle: 'Atlas Path',
      priority: 2,
      tag: 'SECONDARY',
      tagColor: 'purple',
      description: 'Visit Atlas Interfaces, craft Atlas Seeds.',
      unlocks: 'New star types (red/green/blue systems), lore',
      currentQuest: 'Der Staub der Schöpfung',
      tip: 'Do this alongside Artemis when it sends you to an Atlas station.',
      icon: '🔴',
    },
  ],
  secondary: [
    {
      id: 'corvette',
      title: 'Zusammenbau der Korvette',
      subtitle: 'Corvette Assembly',
      priority: 2,
      tag: 'SIDE QUEST',
      tagColor: 'teal',
      description: 'Build your own walkable ship with interior! From the Voyagers Update.',
      unlocks: 'Personal Corvette with walkable interior',
      currentQuest: 'Entwurf eines bewohnbaren Raumschiffs',
      tip: 'Collect Structural Corvette Modules from salvage, pirate battles, frigate expeditions, crashed freighters.',
      icon: '🛸',
    },
    {
      id: 'rebel',
      title: 'Unter dem Rebellenstern',
      subtitle: 'Under a Rebel Star',
      priority: 1,
      tag: 'OPTIONAL',
      tagColor: 'orange',
      description: 'Pirate/Outlaw storyline.',
      unlocks: 'Outlaw station access, unique rewards',
      currentQuest: 'Wider die rote Maschine',
      tip: "Fun but doesn't advance main progression much.",
      icon: '☠️',
    },
    {
      id: 'base',
      title: 'Basiscomputer-Archive',
      subtitle: 'Base Computer Archives',
      priority: 2,
      tag: 'USEFUL',
      tagColor: 'teal',
      description: 'Unlock base building blueprints over time.',
      unlocks: 'Base building blueprints',
      currentQuest: null,
      tip: 'Progress resets on a timer — check back periodically.',
      icon: '🏗️',
    },
    {
      id: 'exploration',
      title: 'Erkundungsanleitung',
      subtitle: 'Exploration Guide',
      priority: 1,
      tag: 'TUTORIAL',
      tagColor: 'gray',
      description: 'Basic exploration tutorials.',
      unlocks: 'Exploration skills',
      currentQuest: 'Lokales Informationsregister',
      tip: 'Basic tutorial, complete it early.',
      icon: '🗺️',
    },
    {
      id: 'photos',
      title: 'Stilvolle Bilder',
      subtitle: 'Stylish Pictures',
      priority: 1,
      tag: 'OPTIONAL',
      tagColor: 'gray',
      description: 'Photo mode missions.',
      unlocks: 'Cosmetic rewards',
      currentQuest: 'Fotos von Landschaften machen',
      tip: 'Fun side activity, do when you feel like it.',
      icon: '📷',
    },
  ],
}

export const inventoryData = {
  sell: [
    { name: 'Gek Relic', value: '~200–400 Units', notes: 'Trade item only, no other use' },
    { name: 'Gek Relics', value: '~200–400 Units', notes: 'Trade item only, no other use' },
    { name: "Vy'keen Dagger", value: '~200–400 Units', notes: 'Trade item only, no other use' },
    { name: "Vy'keen Daggers", value: '~200–400 Units', notes: 'Trade item only, no other use' },
    { name: 'Korvax Casing', value: '~200–400 Units', notes: 'Trade item only, no other use' },
    { name: 'Korvax Casings', value: '~200–400 Units', notes: 'Trade item only, no other use' },
    { name: 'Gravitino Ball', value: '~12,000 Units', notes: 'High value! Sell immediately' },
    { name: 'Gravitino Balls', value: '~12,000 Units', notes: 'High value! Sell immediately' },
    { name: 'Sac Venom', value: '~12,000 Units', notes: 'High value! Sell immediately' },
    { name: 'Larval Core', value: '~65,000 Units', notes: 'Very high value! Priority sell' },
    { name: 'Larval Cores', value: '~65,000 Units', notes: 'Very high value! Priority sell' },
    { name: 'Storm Crystal', value: '~130,000 Units', notes: 'Very high value! Collect during storms, sell immediately' },
    { name: 'Storm Crystals', value: '~130,000 Units', notes: 'Very high value! Collect during storms, sell immediately' },
    { name: 'Ancient Bones', value: 'Varies (up to 2M)', notes: 'Dig up and sell immediately' },
    { name: 'Salvageable Scrap', value: 'Varies', notes: 'Dig up and sell immediately' },
    { name: 'Mordite', value: '~50–100 Units each', notes: 'From killing animals — sell freely, easy to get more' },
    { name: 'Faecium', value: '~50 Units', notes: 'From feeding animals — sell, no real use' },
    { name: 'Rusted Metal', value: '~100 Units', notes: 'Trade item from crashed ships/wrecks — sell immediately' },
    { name: 'Living Slime', value: '~200 Units', notes: 'Trade item from weird creatures — sell immediately' },
    { name: 'Albumen Pearl', value: '~12,000 Units', notes: 'High value! From Abyssal Horrors on ocean floors' },
    { name: 'Hadal Core', value: '~65,000 Units', notes: 'Underwater variant of Larval Core — sell immediately' },
    { name: 'Vile Spawn', value: '~8,000 Units', notes: 'Trade item — sell immediately' },
    { name: 'Whispering Eggs', value: 'DO NOT PICK UP', notes: 'Triggers Biological Horrors — break from a distance, then grab Larval Cores quickly' },
    { name: 'Residual Goop', value: '~50 Units', notes: 'Trade item — sell or refine into slime' },
    { name: 'Viscous Fluids', value: '~75 Units', notes: 'Trade item — sell immediately' },
    { name: 'Fungal Mould', value: '~40 Units', notes: 'From fungal planets — sell freely' },
    { name: 'Frost Crystal', value: '~30 Units', notes: 'From frozen planets — sell excess' },
    { name: 'Solanium', value: '~150 Units', notes: 'From hot/volcanic planets — sell excess' },
    { name: 'Star Bulb', value: '~50 Units', notes: 'From lush planets — sell excess' },
    { name: 'Cactus Flesh', value: '~50 Units', notes: 'From desert planets — sell excess' },
    { name: 'Gamma Root', value: '~80 Units', notes: 'From radioactive planets — sell excess' },
  ],
  keep: [
    { name: 'Ferrite Dust', amount: '500', why: 'Building, repairs' },
    { name: 'Pure Ferrite', amount: '500', why: 'Advanced building' },
    { name: 'Magnetised Ferrite', amount: '250', why: 'Tech crafting' },
    { name: 'Carbon', amount: '500', why: 'Fuel + crafting' },
    { name: 'Condensed Carbon', amount: '250', why: 'Advanced fuel' },
    { name: 'Sodium', amount: '500', why: 'Hazard protection' },
    { name: 'Sodium Nitrate', amount: '250', why: 'Advanced hazard protection' },
    { name: 'Oxygen', amount: '500+', why: 'Life support + Chlorine money trick!' },
    { name: 'Chromatic Metal', amount: '500', why: 'Tech + building' },
    { name: 'Di-Hydrogen', amount: '250', why: 'Starship fuel' },
    { name: 'Cobalt', amount: '250', why: 'Crafting + selling excess' },
    { name: 'Salt', amount: '250', why: 'Chlorine refinement for money trick' },
    { name: 'Chlorine', amount: '250+', why: 'Use in money trick: 1 Chlorine + 2 Oxygen = 6 Chlorine' },
    { name: 'Tritium', amount: '250', why: 'Starship launch fuel + pulse drive — always keep topped up' },
    { name: 'Dihydrogen Jelly', amount: '10', why: 'Emergency Di-Hydrogen — useful on new planets' },
    { name: 'Kelp Sac', amount: '50', why: 'Underwater resource used for Di-Hydrogen Jelly crafting' },
    { name: 'Cyto-Phosphate', amount: '50', why: 'Underwater resource — crafting and tech' },
    { name: 'Ionised Cobalt', amount: '100', why: 'Refine from Cobalt — keeps value high, useful for crafting' },
  ],
  neverSell: [
    { name: 'Warp Cell', why: 'Essential for travel between star systems' },
    { name: 'Warp Cells', why: 'Essential for travel between star systems' },
    { name: 'Antimatter', why: 'Needed to craft Warp Cells' },
    { name: 'Antimatter Housing', why: 'Needed to craft Warp Cells' },
    { name: 'Navigation Data', why: 'Buy maps at space stations' },
    { name: 'Nanite Clusters', why: 'Buy tech upgrades (very important!)' },
    { name: 'Salvaged Data', why: 'Unlock blueprints at Construction Research' },
    { name: 'Atlas Seeds', why: 'Story progression — cannot replace them' },
    { name: 'Corvette Modules', why: 'Building your personal Corvette' },
    { name: 'Pirate Transponder', why: 'Quest item for pirate/outlaw storyline — do NOT sell!' },
    { name: 'Salvaged Frigate Module', why: 'Used to upgrade your freighter fleet — keep every single one' },
    { name: 'Salvaged Frigate Modules', why: 'Used to upgrade your freighter fleet — keep every single one' },
    { name: 'Tainted Metal', why: 'Outlaw currency — use it at outlaw stations, not worth selling' },
    { name: 'Runaway Mould', why: 'Rare self-multiplying resource — keep it, refine into Nanites!' },
    { name: 'Larval Core', why: '65,000 Units each — sell immediately at trade terminal (not keep)' },
  ],
  safeToSell: [
    { name: 'Copper', note: 'Keep ~250 for Chromatic Metal, sell rest' },
    { name: 'Cadmium', note: 'Keep ~250 for Chromatic Metal, sell rest' },
    { name: 'Emeril', note: 'Keep ~250 for Chromatic Metal, sell rest' },
    { name: 'Indium', note: 'Keep ~250 for Chromatic Metal, sell rest (Activated Indium = endgame farm)' },
    { name: 'Activated Copper', note: 'Refine to Chromatic Metal or sell — very valuable' },
    { name: 'Activated Cadmium', note: 'Refine to Chromatic Metal or sell — very valuable' },
    { name: 'Activated Emeril', note: 'Refine to Chromatic Metal or sell — very valuable' },
    { name: 'Activated Indium', note: 'Best farmed in blue star systems — very high value, sell excess' },
    { name: 'Gold', note: 'Keep ~250, sell above that — good value' },
    { name: 'Silver', note: 'Keep ~250, sell above that — good value' },
    { name: 'Platinum', note: 'Keep ~250, sell above that — highest value of the trio' },
    { name: 'Pugneum', note: 'Refine to Gold first or sell directly — from Sentinel drops' },
    { name: 'Paraffinium', note: 'Planet resource (lush worlds), easy to find again' },
    { name: 'Phosphorus', note: 'Planet resource (hot worlds), easy to find again' },
    { name: 'Dioxite', note: 'Planet resource (frozen worlds), easy to find again' },
    { name: 'Pyrite', note: 'Planet resource (volcanic worlds), easy to find again' },
    { name: 'Ammonia', note: 'Planet resource, sell excess freely' },
    { name: 'Uranium', note: 'Planet resource, sell excess freely' },
    { name: 'Geode', note: 'Decorative/trade item — sell at Galactic Trade Terminal for decent price' },
    { name: 'Dirty Bronze', note: 'From scrap — refine or sell' },
    { name: 'Herox', note: 'From refinement — sell excess' },
    { name: 'Lemmium', note: 'From refinement — sell excess' },
    { name: 'Magno-Gold', note: 'From refinement — sell excess' },
  ],
}

export const moneyMakingData = [
  {
    id: 'chlorine',
    rank: 1,
    title: 'Chlorine + Oxygen Refiner Trick',
    badge: 'BEST METHOD',
    badgeColor: 'gold',
    icon: '🏆',
    requirements: 'Medium or Large Refiner',
    recipe: '1 Chlorine + 2 Oxygen → 6 Chlorine',
    profit: 'Millions in 30 minutes!',
    steps: [
      'Buy a small amount of Chlorine at any space station',
      'Buy LOTS of Oxygen (cheap, available everywhere)',
      'Put 1 Chlorine + 2 Oxygen in Medium Refiner',
      'Get 6 Chlorine out → repeat!',
      'Sell Chlorine stacks for ~600 Units each',
    ],
  },
  {
    id: 'scrapping',
    rank: 2,
    title: 'Ship Scrapping',
    badge: 'EASY MONEY',
    badgeColor: 'green',
    icon: '💰',
    requirements: 'Space Station access',
    recipe: null,
    profit: 'Hundreds of thousands + Nanites',
    steps: [
      'Go to any space station',
      'Buy cheap ships from landing NPCs',
      'Scrap them at the Ship Scrapper terminal',
      'Sell the scrap materials',
      'Bonus: get upgrade modules to sell for Nanites!',
    ],
  },
  {
    id: 'scrap-refining',
    rank: 3,
    title: 'Metal Scrap Refining',
    badge: 'PASSIVE',
    badgeColor: 'blue',
    icon: '⚙️',
    requirements: 'Refiner + combat',
    recipe: 'Pugneum → Gold/Silver',
    profit: 'Good passive income alongside combat',
    steps: [
      'Fight pirates or Sentinels to get Pugneum',
      'Refine Pugneum → Gold or Silver',
      'Sell at Galactic Trade Terminal',
    ],
  },
  {
    id: 'indium',
    rank: 4,
    title: 'Activated Indium Farm',
    badge: 'ENDGAME',
    badgeColor: 'purple',
    icon: '🏭',
    requirements: 'Blue star system (Indium Drive) + base building',
    recipe: null,
    profit: 'Passive millions while you do other things',
    steps: [
      'Get an Indium Drive hyperdrive upgrade',
      'Travel to a blue star system',
      'Find an Activated Indium deposit',
      'Build mineral extractors + supply depots',
      'Come back to collect millions passively',
    ],
  },
  {
    id: 'bones',
    rank: 5,
    title: 'Ancient Bones / Salvageable Scrap',
    badge: 'EXPLORATION',
    badgeColor: 'teal',
    icon: '🦴',
    requirements: 'Scanner + Geological Cannon',
    recipe: null,
    profit: 'Some bones worth 1–2 million each!',
    steps: [
      'Scan planets from space — look for "Ancient Bones" or "Salvageable Scrap"',
      'Land and activate your scanner',
      'Dig up the markers with Terrain Manipulator',
      'Sell immediately at trade terminal',
    ],
  },
]

export const shipsData = {
  types: [
    { type: 'Fighter', bestFor: 'Combat', special: 'High damage, bonus shield', icon: '⚔️' },
    { type: 'Explorer', bestFor: 'Warp range', special: 'Hyperdrive distance bonus', icon: '🔭' },
    { type: 'Hauler', bestFor: 'Storage', special: 'Most cargo slots', icon: '📦' },
    { type: 'Shuttle', bestFor: 'Budget all-rounder', special: 'Cheap to buy', icon: '🚀' },
    { type: 'Exotic', bestFor: 'Collection / Style', special: 'Rare, unique appearance', icon: '✨' },
    { type: 'Solar', bestFor: 'Style + efficiency', special: 'Solar sails recharge for free', icon: '☀️' },
    { type: 'Living Ship', bestFor: 'Endgame unique', special: 'Organic, grows and evolves', icon: '🌱' },
    { type: 'Corvette', bestFor: 'Walkable interior', special: 'Build your own via quest!', icon: '🛸' },
  ],
  classes: [
    { class: 'C', quality: 'Basic', price: 'Cheapest', color: 'gray' },
    { class: 'B', quality: 'Good', price: 'Medium', color: 'green' },
    { class: 'A', quality: 'Great', price: 'Expensive', color: 'blue' },
    { class: 'S', quality: 'Best', price: 'Very expensive', color: 'gold' },
  ],
  howToGet: [
    { method: 'Space Station Trading', desc: 'NPCs land constantly with ships. Walk up, interact, buy or trade.', icon: '🏪' },
    { method: 'Trading Posts', desc: 'More ships land simultaneously = more choices at once.', icon: '📡' },
    { method: 'Free Freighter', desc: 'After ~5 hyperspace warps, a space battle triggers. Save the captain → get the freighter FREE!', icon: '🎁' },
    { method: 'Crashed Ships', desc: 'Find on planets, repair and claim for free (needs repairs).', icon: '💥' },
    { method: 'Build a Corvette', desc: 'Complete the "Zusammenbau der Korvette" quest line.', icon: '🔨' },
  ],
}

export const refinerData = [
  { input: '1 Chlorine + 2 Oxygen', output: '6 Chlorine', notes: 'Money printing trick! 💰', highlight: true },
  { input: 'Salt', output: 'Chlorine', notes: 'Start the money trick with this' },
  { input: 'Ferrite Dust', output: 'Pure Ferrite', notes: 'Basic upgrade' },
  { input: 'Pure Ferrite', output: 'Magnetised Ferrite', notes: 'Advanced upgrade' },
  { input: 'Carbon', output: 'Condensed Carbon', notes: 'Fuel upgrade' },
  { input: 'Cobalt', output: 'Ionised Cobalt', notes: 'Value x6 — good to refine before selling' },
  { input: 'Copper', output: 'Chromatic Metal', notes: 'Essential tech resource' },
  { input: 'Pugneum', output: 'Gold', notes: 'From combat drops' },
  { input: 'Runaway Mould', output: 'Nanite Clusters', notes: 'Rare but very useful — self-multiplies!' },
]

export const quickTipsData = {
  tips: [
    { icon: '🔍', tip: 'Scan everything! With S-class scanner upgrades, each creature scan = 100k–400k Units' },
    { icon: '📡', tip: 'Upload discoveries at the Space Anomaly for free Nanite Clusters' },
    { icon: '💹', tip: 'Check Galactic Trade Terminal prices — buy low in one system, sell high in another' },
    { icon: '📍', tip: 'Use a Signal Booster to find nearby points of interest (crashed ships, ruins, etc.)' },
    { icon: '💾', tip: 'Save often! Use save points on the ground or your ship landing' },
    { icon: '⭐', tip: 'Yellow star icon on an item = Trade Item = sell it immediately!' },
    { icon: '🌟', tip: '3-star economy systems have better ships and higher item prices' },
    { icon: '🔄', tip: 'Always check the ship comparison screen before buying — trade-in value is deducted' },
    { icon: '🛡️', tip: 'Refill hazard protection with Sodium or Sodium Nitrate on extreme planets' },
    { icon: '💎', tip: 'S-class upgrade modules from scrapping give massive Nanite profits' },
  ],
  techToInstall: [
    { name: 'Scanner Upgrades (S-class)', why: 'Huge bonus for scanning flora/fauna — biggest early money maker' },
    { name: 'Hazard Protection Upgrades', why: 'Survive extreme planets, unlock more of the galaxy' },
    { name: 'Hyperdrive Upgrades', why: 'Reach further, wealthier systems faster' },
    { name: 'Mining Beam Upgrades', why: 'Mine resources much faster' },
    { name: 'Jetpack Upgrades', why: 'Better mobility in exploration and combat' },
  ],
}

// ─────────────────────────────────────────────────────────────────────────────
// ITEM DATABASE — The complete sell/keep reference
// ─────────────────────────────────────────────────────────────────────────────

export const itemDatabase = [
  // ── NEVER SELL (red) ──────────────────────────────────────────────────────
  { name: 'Warp Cell', verdict: 'never', label: 'NEVER SELL', reason: 'Essential for warp travel between star systems' },
  { name: 'Warp Cells', verdict: 'never', label: 'NEVER SELL', reason: 'Essential for warp travel between star systems' },
  { name: 'Antimatter', verdict: 'never', label: 'NEVER SELL', reason: 'Needed to craft Warp Cells — always keep it' },
  { name: 'Antimatter Housing', verdict: 'never', label: 'NEVER SELL', reason: 'Needed to craft Warp Cells — always keep it' },
  { name: 'Nanite Clusters', verdict: 'never', label: 'NEVER SELL', reason: 'Currency for buying tech upgrades — extremely valuable' },
  { name: 'Salvaged Data', verdict: 'never', label: 'NEVER SELL', reason: 'Used to unlock blueprints at Construction Research Station' },
  { name: 'Navigation Data', verdict: 'never', label: 'NEVER SELL', reason: 'Buy maps at space stations — always useful' },
  { name: 'Atlas Seeds', verdict: 'never', label: 'NEVER SELL', reason: 'Main story progression items — cannot be replaced!' },
  { name: 'Atlas Stone', verdict: 'never', label: 'NEVER SELL', reason: 'Story item — do not sell' },
  { name: 'Corvette Modules', verdict: 'never', label: 'NEVER SELL', reason: 'Used to build your personal Corvette ship' },
  { name: 'Pirate Transponder', verdict: 'never', label: 'NEVER SELL', reason: 'Quest item for the pirate storyline — irreplaceable!' },
  { name: 'Salvaged Frigate Module', verdict: 'never', label: 'NEVER SELL', reason: 'Used to upgrade your freighter fleet — every one counts' },
  { name: 'Tainted Metal', verdict: 'never', label: 'NEVER SELL', reason: 'Outlaw currency — spend it at outlaw stations instead' },
  { name: 'Runaway Mould', verdict: 'never', label: 'NEVER SELL', reason: 'Self-multiplying! Refine into Nanite Clusters — golden resource' },
  { name: 'Mind Arc', verdict: 'never', label: 'NEVER SELL', reason: 'Story/quest item — do not sell' },
  { name: 'Larval Core', verdict: 'sell', label: 'SELL NOW', reason: '~65,000 Units each! Sell immediately at trade terminal' },
  { name: 'Larval Cores', verdict: 'sell', label: 'SELL NOW', reason: '~65,000 Units each! Sell immediately at trade terminal' },

  // ── SELL IMMEDIATELY (green) ─────────────────────────────────────────────
  { name: 'Gek Relic', verdict: 'sell', label: 'SELL IT', reason: 'Trade item only — ~200-400 Units each, no other use' },
  { name: 'Gek Relics', verdict: 'sell', label: 'SELL IT', reason: 'Trade item only — ~200-400 Units each, no other use' },
  { name: "Vy'keen Dagger", verdict: 'sell', label: 'SELL IT', reason: 'Trade item only — ~200-400 Units each, no other use' },
  { name: "Vy'keen Daggers", verdict: 'sell', label: 'SELL IT', reason: 'Trade item only — ~200-400 Units each, no other use' },
  { name: 'Korvax Casing', verdict: 'sell', label: 'SELL IT', reason: 'Trade item only — ~200-400 Units each, no other use' },
  { name: 'Korvax Casings', verdict: 'sell', label: 'SELL IT', reason: 'Trade item only — ~200-400 Units each, no other use' },
  { name: 'Gravitino Ball', verdict: 'sell', label: 'SELL IT', reason: '~12,000 Units — high value trade item. Sentinels will attack when picked up!' },
  { name: 'Gravitino Balls', verdict: 'sell', label: 'SELL IT', reason: '~12,000 Units — high value trade item. Sentinels will attack when picked up!' },
  { name: 'Sac Venom', verdict: 'sell', label: 'SELL IT', reason: '~12,000 Units — high value. From cave creatures. Sell immediately' },
  { name: 'Storm Crystal', verdict: 'sell', label: 'SELL IT', reason: '~130,000 Units! Collect during storms, sell immediately' },
  { name: 'Storm Crystals', verdict: 'sell', label: 'SELL IT', reason: '~130,000 Units! Collect during storms, sell immediately' },
  { name: 'Ancient Bones', verdict: 'sell', label: 'SELL IT', reason: 'Up to 2 Million Units! Dig up with Terrain Manipulator and sell' },
  { name: 'Salvageable Scrap', verdict: 'sell', label: 'SELL IT', reason: 'Good value — dig up and sell immediately' },
  { name: 'Albumen Pearl', verdict: 'sell', label: 'SELL IT', reason: '~12,000 Units! Found in underwater Abyssal Horror nests' },
  { name: 'Hadal Core', verdict: 'sell', label: 'SELL IT', reason: '~65,000 Units — underwater equivalent of Larval Core. Sell immediately!' },
  { name: 'Vile Spawn', verdict: 'sell', label: 'SELL IT', reason: 'Trade item — sell immediately for decent price' },
  { name: 'Residual Goop', verdict: 'sell', label: 'SELL IT', reason: 'Trade item — sell or refine into Living Slime' },
  { name: 'Viscous Fluids', verdict: 'sell', label: 'SELL IT', reason: 'Trade item — sell immediately' },
  { name: 'Living Slime', verdict: 'sell', label: 'SELL IT', reason: 'Trade item from weird creatures — sell immediately' },
  { name: 'Mordite', verdict: 'sell', label: 'SELL IT', reason: 'From killing animals — ~50-100 Units each, easy to farm, sell freely' },
  { name: 'Faecium', verdict: 'sell', label: 'SELL IT', reason: 'From feeding animals — low value, no real use, sell it' },
  { name: 'Rusted Metal', verdict: 'sell', label: 'SELL IT', reason: 'From crashed ships/wrecks — trade item, sell immediately' },
  { name: 'Fungal Mould', verdict: 'sell', label: 'SELL IT', reason: 'From fungal planets — sell excess freely' },
  { name: 'Frost Crystal', verdict: 'sell', label: 'SELL IT', reason: 'From frozen planets — sell excess freely' },
  { name: 'Solanium', verdict: 'sell', label: 'SELL IT', reason: 'From hot/volcanic planets — sell excess freely' },
  { name: 'Star Bulb', verdict: 'sell', label: 'SELL IT', reason: 'From lush planets — sell excess freely' },
  { name: 'Cactus Flesh', verdict: 'sell', label: 'SELL IT', reason: 'From desert planets — sell excess freely' },
  { name: 'Gamma Root', verdict: 'sell', label: 'SELL IT', reason: 'From radioactive planets — sell excess freely' },

  // ── KEEP (yellow) ────────────────────────────────────────────────────────
  { name: 'Ferrite Dust', verdict: 'keep', label: 'KEEP SOME', reason: 'Keep ~500. Used constantly for building and repairs' },
  { name: 'Pure Ferrite', verdict: 'keep', label: 'KEEP SOME', reason: 'Keep ~500. Advanced building material' },
  { name: 'Magnetised Ferrite', verdict: 'keep', label: 'KEEP SOME', reason: 'Keep ~250. Tech crafting ingredient' },
  { name: 'Carbon', verdict: 'keep', label: 'KEEP SOME', reason: 'Keep ~500. Fuel for many things + crafting staple' },
  { name: 'Condensed Carbon', verdict: 'keep', label: 'KEEP SOME', reason: 'Keep ~250. Advanced fuel and crafting' },
  { name: 'Sodium', verdict: 'keep', label: 'KEEP SOME', reason: 'Keep ~500. Refills hazard protection on extreme planets' },
  { name: 'Sodium Nitrate', verdict: 'keep', label: 'KEEP SOME', reason: 'Keep ~250. Advanced hazard protection' },
  { name: 'Oxygen', verdict: 'keep', label: 'KEEP SOME', reason: 'Keep 500+. Life support + used in Chlorine money trick!' },
  { name: 'Chromatic Metal', verdict: 'keep', label: 'KEEP SOME', reason: 'Keep ~500. Used everywhere for tech and building' },
  { name: 'Di-Hydrogen', verdict: 'keep', label: 'KEEP SOME', reason: 'Keep ~250. Starship launch fuel — always keep topped up' },
  { name: 'Cobalt', verdict: 'keep', label: 'KEEP SOME', reason: 'Keep ~250. Crafting ingredient — refine excess into Ionised Cobalt first' },
  { name: 'Salt', verdict: 'keep', label: 'KEEP SOME', reason: 'Keep ~250. Refine into Chlorine for the money trick' },
  { name: 'Chlorine', verdict: 'keep', label: 'KEEP SOME', reason: 'Core of the money trick: 1 Chlorine + 2 Oxygen = 6 Chlorine in refiner!' },
  { name: 'Tritium', verdict: 'keep', label: 'KEEP SOME', reason: 'Keep ~250. Starship pulse drive fuel — collect from asteroids' },
  { name: 'Kelp Sac', verdict: 'keep', label: 'KEEP SOME', reason: 'Keep ~50. Underwater resource, useful for crafting Di-Hydrogen Jelly' },
  { name: 'Cyto-Phosphate', verdict: 'keep', label: 'KEEP SOME', reason: 'Keep ~50. Underwater resource for crafting and tech' },
  { name: 'Ionised Cobalt', verdict: 'keep', label: 'KEEP SOME', reason: 'Keep ~100. Refine from Cobalt — good crafting ingredient and sell value' },
  { name: 'Dihydrogen Jelly', verdict: 'keep', label: 'KEEP SOME', reason: 'Keep a few. Emergency Di-Hydrogen — good backup on new planets' },

  // ── SAFE TO SELL / SELL EXCESS (cyan) ───────────────────────────────────
  { name: 'Copper', verdict: 'safe', label: 'SELL EXCESS', reason: 'Keep ~250 for Chromatic Metal, sell the rest' },
  { name: 'Cadmium', verdict: 'safe', label: 'SELL EXCESS', reason: 'Keep ~250 for Chromatic Metal, sell the rest' },
  { name: 'Emeril', verdict: 'safe', label: 'SELL EXCESS', reason: 'Keep ~250 for Chromatic Metal, sell the rest' },
  { name: 'Indium', verdict: 'safe', label: 'SELL EXCESS', reason: 'Keep ~250 for Chromatic Metal; Activated Indium is endgame farm material' },
  { name: 'Activated Copper', verdict: 'safe', label: 'SELL EXCESS', reason: 'Very high value — refine into Chromatic Metal or sell directly' },
  { name: 'Activated Cadmium', verdict: 'safe', label: 'SELL EXCESS', reason: 'Very high value — refine into Chromatic Metal or sell directly' },
  { name: 'Activated Emeril', verdict: 'safe', label: 'SELL EXCESS', reason: 'Very high value — refine into Chromatic Metal or sell directly' },
  { name: 'Activated Indium', verdict: 'safe', label: 'SELL EXCESS', reason: 'Highest value resource — farm in blue star systems, sell excess for millions' },
  { name: 'Gold', verdict: 'safe', label: 'SELL EXCESS', reason: 'Keep ~250, sell above that — good trade value' },
  { name: 'Silver', verdict: 'safe', label: 'SELL EXCESS', reason: 'Keep ~250, sell above that — good trade value' },
  { name: 'Platinum', verdict: 'safe', label: 'SELL EXCESS', reason: 'Keep ~250, sell above that — highest value of the precious metals' },
  { name: 'Pugneum', verdict: 'safe', label: 'SELL EXCESS', reason: 'From Sentinel drops — refine into Gold first, or sell directly' },
  { name: 'Paraffinium', verdict: 'safe', label: 'SELL EXCESS', reason: 'Lush planet resource — easy to find again, sell excess freely' },
  { name: 'Phosphorus', verdict: 'safe', label: 'SELL EXCESS', reason: 'Hot planet resource — easy to find again, sell excess freely' },
  { name: 'Dioxite', verdict: 'safe', label: 'SELL EXCESS', reason: 'Frozen planet resource — easy to find again, sell excess freely' },
  { name: 'Pyrite', verdict: 'safe', label: 'SELL EXCESS', reason: 'Volcanic planet resource — easy to find again, sell excess freely' },
  { name: 'Ammonia', verdict: 'safe', label: 'SELL EXCESS', reason: 'Planet resource — sell excess freely' },
  { name: 'Uranium', verdict: 'safe', label: 'SELL EXCESS', reason: 'Planet resource — sell excess freely' },
  { name: 'Geode', verdict: 'safe', label: 'SELL EXCESS', reason: 'Decorative trade item — sell at Galactic Trade Terminal for decent price' },
  { name: 'Dirty Bronze', verdict: 'safe', label: 'SELL EXCESS', reason: 'From scrap refining — refine for better value or sell directly' },
  { name: 'Herox', verdict: 'safe', label: 'SELL EXCESS', reason: 'From refinement — sell excess freely' },
  { name: 'Lemmium', verdict: 'safe', label: 'SELL EXCESS', reason: 'From refinement — sell excess freely' },
  { name: 'Magno-Gold', verdict: 'safe', label: 'SELL EXCESS', reason: 'From refinement — sell excess freely' },
]

// ── Legacy flat list for backward compat ─────────────────────────────────────
export const allItems = itemDatabase.map(item => ({
  name: item.name,
  category: item.verdict,
  detail: item.reason,
}))
