export const missionsData = {
  primary: [
    {
      id: 'artemis',
      title: 'Allein inmitten der Sterne',
      subtitle: 'Artemis Path',
      priority: 3,
      tag: 'MAIN STORY',
      tagColor: 'cyan',
      description: 'The main storyline following Artemis, the explorer.',
      unlocks: 'Portals, new galaxies, most game features',
      currentQuest: 'Artemis, der Entdecker',
      tip: 'This drives progression the most. Focus here first!',
      icon: '🌌',
    },
    {
      id: 'anomaly',
      title: 'Die Weltraumanomalie',
      subtitle: 'Space Anomaly',
      priority: 3,
      tag: 'PARALLEL',
      tagColor: 'blue',
      description: 'Introduces the Nexus (multiplayer hub), Nada & Polo.',
      unlocks: 'Blueprints, multiplayer missions, Nexus shop',
      currentQuest: 'Jenseits des Systems?',
      tip: 'Runs parallel to Artemis Path. Visit the Anomaly when prompted.',
      icon: '🔮',
    },
    {
      id: 'atlas',
      title: 'Der Weg des Atlas',
      subtitle: 'Atlas Path',
      priority: 2,
      tag: 'SECONDARY',
      tagColor: 'purple',
      description: 'Visit Atlas Interfaces, craft Atlas Seeds.',
      unlocks: 'New star types (red/green/blue systems), lore',
      currentQuest: 'Der Staub der Schöpfung',
      tip: 'Do this alongside Artemis when it sends you to an Atlas station.',
      icon: '🔴',
    },
  ],
  secondary: [
    {
      id: 'corvette',
      title: 'Zusammenbau der Korvette',
      subtitle: 'Corvette Assembly',
      priority: 2,
      tag: 'SIDE QUEST',
      tagColor: 'teal',
      description: 'Build your own walkable ship with interior! From the Voyagers Update.',
      unlocks: 'Personal Corvette with walkable interior',
      currentQuest: 'Entwurf eines bewohnbaren Raumschiffs',
      tip: 'Collect Structural Corvette Modules from salvage, pirate battles, frigate expeditions, crashed freighters.',
      icon: '🛸',
    },
    {
      id: 'rebel',
      title: 'Unter dem Rebellenstern',
      subtitle: 'Under a Rebel Star',
      priority: 1,
      tag: 'OPTIONAL',
      tagColor: 'orange',
      description: 'Pirate/Outlaw storyline.',
      unlocks: 'Outlaw station access, unique rewards',
      currentQuest: 'Wider die rote Maschine',
      tip: "Fun but doesn't advance main progression much.",
      icon: '☠️',
    },
    {
      id: 'base',
      title: 'Basiscomputer-Archive',
      subtitle: 'Base Computer Archives',
      priority: 2,
      tag: 'USEFUL',
      tagColor: 'teal',
      description: 'Unlock base building blueprints over time.',
      unlocks: 'Base building blueprints',
      currentQuest: null,
      tip: 'Progress resets on a timer — check back periodically.',
      icon: '🏗️',
    },
    {
      id: 'exploration',
      title: 'Erkundungsanleitung',
      subtitle: 'Exploration Guide',
      priority: 1,
      tag: 'TUTORIAL',
      tagColor: 'gray',
      description: 'Basic exploration tutorials.',
      unlocks: 'Exploration skills',
      currentQuest: 'Lokales Informationsregister',
      tip: 'Basic tutorial, complete it early.',
      icon: '🗺️',
    },
    {
      id: 'photos',
      title: 'Stilvolle Bilder',
      subtitle: 'Stylish Pictures',
      priority: 1,
      tag: 'OPTIONAL',
      tagColor: 'gray',
      description: 'Photo mode missions.',
      unlocks: 'Cosmetic rewards',
      currentQuest: 'Fotos von Landschaften machen',
      tip: 'Fun side activity, do when you feel like it.',
      icon: '📷',
    },
  ],
}

export const inventoryData = {
  sell: [
    { name: 'Gek Relics', value: '~200–400 Units', notes: 'Trade item only, no other use' },
    { name: "Vy'keen Daggers", value: '~200–400 Units', notes: 'Trade item only, no other use' },
    { name: 'Korvax Casings', value: '~200–400 Units', notes: 'Trade item only, no other use' },
    { name: 'Gravitino Balls', value: '~12,000 Units', notes: 'High value! Sell immediately' },
    { name: 'Sac Venom', value: '~12,000 Units', notes: 'High value! Sell immediately' },
    { name: 'Larval Cores', value: '~65,000 Units', notes: 'Very high value! Priority sell' },
    { name: 'Storm Crystals', value: '~130,000 Units', notes: 'Very high value! Priority sell' },
    { name: 'Ancient Bones', value: 'Varies (up to 2M)', notes: 'Dig up and sell immediately' },
    { name: 'Salvageable Scrap', value: 'Varies', notes: 'Dig up and sell immediately' },
  ],
  keep: [
    { name: 'Ferrite Dust', amount: '500', why: 'Building, repairs' },
    { name: 'Pure Ferrite', amount: '500', why: 'Advanced building' },
    { name: 'Magnetised Ferrite', amount: '250', why: 'Tech crafting' },
    { name: 'Carbon', amount: '500', why: 'Fuel + crafting' },
    { name: 'Condensed Carbon', amount: '250', why: 'Advanced fuel' },
    { name: 'Sodium', amount: '500', why: 'Hazard protection' },
    { name: 'Sodium Nitrate', amount: '250', why: 'Advanced hazard protection' },
    { name: 'Oxygen', amount: '500+', why: 'Life support + Chlorine money trick!' },
    { name: 'Chromatic Metal', amount: '500', why: 'Tech + building' },
    { name: 'Di-Hydrogen', amount: '250', why: 'Starship fuel' },
    { name: 'Cobalt', amount: '250', why: 'Crafting + selling excess' },
    { name: 'Salt', amount: '250', why: 'Chlorine refinement for money trick' },
  ],
  neverSell: [
    { name: 'Warp Cells', why: 'Essential for travel between star systems' },
    { name: 'Antimatter', why: 'Needed to craft Warp Cells' },
    { name: 'Antimatter Housing', why: 'Needed to craft Warp Cells' },
    { name: 'Navigation Data', why: 'Buy maps at space stations' },
    { name: 'Nanite Clusters', why: 'Buy tech upgrades (very important!)' },
    { name: 'Salvaged Data', why: 'Unlock blueprints at Construction Research' },
    { name: 'Atlas Seeds', why: 'Story progression — cannot replace them' },
    { name: 'Corvette Modules', why: 'Building your personal Corvette' },
  ],
  safeToSell: [
    { name: 'Copper, Cadmium, Emeril, Indium', note: 'Keep ~250 for Chromatic Metal, sell rest' },
    { name: 'Gold, Silver, Platinum', note: 'Valuable — sell extras above 250' },
    { name: 'Pugneum', note: 'Refine to Gold first or sell directly' },
    { name: 'Paraffinium, Phosphorus, Dioxite, Pyrite', note: 'Planet resources, easy to find again' },
    { name: 'Ammonia, Uranium', note: 'Planet resources, sell excess freely' },
  ],
}

export const moneyMakingData = [
  {
    id: 'chlorine',
    rank: 1,
    title: 'Chlorine + Oxygen Refiner Trick',
    badge: 'BEST METHOD',
    badgeColor: 'gold',
    icon: '🏆',
    requirements: 'Medium or Large Refiner',
    recipe: '1 Chlorine + 2 Oxygen → 6 Chlorine',
    profit: 'Millions in 30 minutes!',
    steps: [
      'Buy a small amount of Chlorine at any space station',
      'Buy LOTS of Oxygen (cheap, available everywhere)',
      'Put 1 Chlorine + 2 Oxygen in Medium Refiner',
      'Get 6 Chlorine out → repeat!',
      'Sell Chlorine stacks for ~600 Units each',
    ],
  },
  {
    id: 'scrapping',
    rank: 2,
    title: 'Ship Scrapping',
    badge: 'EASY MONEY',
    badgeColor: 'green',
    icon: '💰',
    requirements: 'Space Station access',
    recipe: null,
    profit: 'Hundreds of thousands + Nanites',
    steps: [
      'Go to any space station',
      'Buy cheap ships from landing NPCs',
      'Scrap them at the Ship Scrapper terminal',
      'Sell the scrap materials',
      'Bonus: get upgrade modules to sell for Nanites!',
    ],
  },
  {
    id: 'scrap-refining',
    rank: 3,
    title: 'Metal Scrap Refining',
    badge: 'PASSIVE',
    badgeColor: 'blue',
    icon: '⚙️',
    requirements: 'Refiner + combat',
    recipe: 'Pugneum → Gold/Silver',
    profit: 'Good passive income alongside combat',
    steps: [
      'Fight pirates or Sentinels to get Pugneum',
      'Refine Pugneum → Gold or Silver',
      'Sell at Galactic Trade Terminal',
    ],
  },
  {
    id: 'indium',
    rank: 4,
    title: 'Activated Indium Farm',
    badge: 'ENDGAME',
    badgeColor: 'purple',
    icon: '🏭',
    requirements: 'Blue star system (Indium Drive) + base building',
    recipe: null,
    profit: 'Passive millions while you do other things',
    steps: [
      'Get an Indium Drive hyperdrive upgrade',
      'Travel to a blue star system',
      'Find an Activated Indium deposit',
      'Build mineral extractors + supply depots',
      'Come back to collect millions passively',
    ],
  },
  {
    id: 'bones',
    rank: 5,
    title: 'Ancient Bones / Salvageable Scrap',
    badge: 'EXPLORATION',
    badgeColor: 'teal',
    icon: '🦴',
    requirements: 'Scanner + Geological Cannon',
    recipe: null,
    profit: 'Some bones worth 1–2 million each!',
    steps: [
      'Scan planets from space — look for "Ancient Bones" or "Salvageable Scrap"',
      'Land and activate your scanner',
      'Dig up the markers with Terrain Manipulator',
      'Sell immediately at trade terminal',
    ],
  },
]

export const shipsData = {
  types: [
    { type: 'Fighter', bestFor: 'Combat', special: 'High damage, bonus shield', icon: '⚔️' },
    { type: 'Explorer', bestFor: 'Warp range', special: 'Hyperdrive distance bonus', icon: '🔭' },
    { type: 'Hauler', bestFor: 'Storage', special: 'Most cargo slots', icon: '📦' },
    { type: 'Shuttle', bestFor: 'Budget all-rounder', special: 'Cheap to buy', icon: '🚀' },
    { type: 'Exotic', bestFor: 'Collection / Style', special: 'Rare, unique appearance', icon: '✨' },
    { type: 'Solar', bestFor: 'Style + efficiency', special: 'Solar sails recharge for free', icon: '☀️' },
    { type: 'Living Ship', bestFor: 'Endgame unique', special: 'Organic, grows and evolves', icon: '🌱' },
    { type: 'Corvette', bestFor: 'Walkable interior', special: 'Build your own via quest!', icon: '🛸' },
  ],
  classes: [
    { class: 'C', quality: 'Basic', price: 'Cheapest', color: 'gray' },
    { class: 'B', quality: 'Good', price: 'Medium', color: 'green' },
    { class: 'A', quality: 'Great', price: 'Expensive', color: 'blue' },
    { class: 'S', quality: 'Best', price: 'Very expensive', color: 'gold' },
  ],
  howToGet: [
    { method: 'Space Station Trading', desc: 'NPCs land constantly with ships. Walk up, interact, buy or trade.', icon: '🏪' },
    { method: 'Trading Posts', desc: 'More ships land simultaneously = more choices at once.', icon: '📡' },
    { method: 'Free Freighter', desc: 'After ~5 hyperspace warps, a space battle triggers. Save the captain → get the freighter FREE!', icon: '🎁' },
    { method: 'Crashed Ships', desc: 'Find on planets, repair and claim for free (needs repairs).', icon: '💥' },
    { method: 'Build a Corvette', desc: 'Complete the "Zusammenbau der Korvette" quest line.', icon: '🔨' },
  ],
}

export const refinerData = [
  { input: '1 Chlorine + 2 Oxygen', output: '6 Chlorine', notes: 'Money printing trick! 💰', highlight: true },
  { input: 'Salt', output: 'Chlorine', notes: 'Start the money trick with this' },
  { input: 'Ferrite Dust', output: 'Pure Ferrite', notes: 'Basic upgrade' },
  { input: 'Pure Ferrite', output: 'Magnetised Ferrite', notes: 'Advanced upgrade' },
  { input: 'Carbon', output: 'Condensed Carbon', notes: 'Fuel upgrade' },
  { input: 'Cobalt', output: 'Ionised Cobalt', notes: 'Value x6 — good to refine before selling' },
  { input: 'Copper', output: 'Chromatic Metal', notes: 'Essential tech resource' },
  { input: 'Pugneum', output: 'Gold', notes: 'From combat drops' },
]

export const quickTipsData = {
  tips: [
    { icon: '🔍', tip: 'Scan everything! With S-class scanner upgrades, each creature scan = 100k–400k Units' },
    { icon: '📡', tip: 'Upload discoveries at the Space Anomaly for free Nanite Clusters' },
    { icon: '💹', tip: 'Check Galactic Trade Terminal prices — buy low in one system, sell high in another' },
    { icon: '📍', tip: 'Use a Signal Booster to find nearby points of interest (crashed ships, ruins, etc.)' },
    { icon: '💾', tip: 'Save often! Use save points on the ground or your ship landing' },
    { icon: '⭐', tip: 'Yellow star icon on an item = Trade Item = sell it immediately!' },
    { icon: '🌟', tip: '3-star economy systems have better ships and higher item prices' },
    { icon: '🔄', tip: 'Always check the ship comparison screen before buying — trade-in value is deducted' },
    { icon: '🛡️', tip: 'Refill hazard protection with Sodium or Sodium Nitrate on extreme planets' },
    { icon: '💎', tip: 'S-class upgrade modules from scrapping give massive Nanite profits' },
  ],
  techToInstall: [
    { name: 'Scanner Upgrades (S-class)', why: 'Huge bonus for scanning flora/fauna — biggest early money maker' },
    { name: 'Hazard Protection Upgrades', why: 'Survive extreme planets, unlock more of the galaxy' },
    { name: 'Hyperdrive Upgrades', why: 'Reach further, wealthier systems faster' },
    { name: 'Mining Beam Upgrades', why: 'Mine resources much faster' },
    { name: 'Jetpack Upgrades', why: 'Better mobility in exploration and combat' },
  ],
}

// All searchable items flattened for Quick Sell Check
export const allItems = [
  // Sell items
  ...inventoryData.sell.map(i => ({ name: i.name, category: 'sell', detail: `Sell immediately — ${i.value}. ${i.notes}` })),
  // Keep items
  ...inventoryData.keep.map(i => ({ name: i.name, category: 'keep', detail: `Keep ~${i.amount}. ${i.why}` })),
  // Never sell items
  ...inventoryData.neverSell.map(i => ({ name: i.name, category: 'never', detail: `NEVER sell! ${i.why}` })),
  // Safe to sell
  ...inventoryData.safeToSell.map(i => ({ name: i.name, category: 'safe', detail: i.note })),
  // Resources
  { name: 'Chlorine', category: 'keep', detail: 'Use in money trick: 1 Chlorine + 2 Oxygen = 6 Chlorine' },
  { name: 'Ionised Cobalt', category: 'safe', detail: 'Refine from Cobalt first, then sell for better price' },
  { name: 'Activated Indium', category: 'keep', detail: 'Extremely valuable — farm it, keep for endgame' },
]
